export const AUTH_ATTEMPTING = 'AUTH_ATTEMPTING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const PROFILE_FETCHED = 'PROFILE_FETCHED';

export const EXPENSE_SAVED = 'EXPENSE_SAVED';
export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const RESET_SAVED_FLAG = 'RESET_SAVED_FLAG';