export const AUTH_ATTEMPTING = 'AUTH_ATTEMPTING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const PROFILE_FETCHED = 'PROFILE_FETCHED';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const RESET_CREATED_FLAG = 'RESET_CREATED_FLAG';

export const EXPENSE_SAVED = 'EXPENSE_SAVED';
export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const RESET_SAVED_FLAG = 'RESET_SAVED_FLAG';

export const FETCHING_EXPENSES = 'FETCHING_EXPENSES';
export const EXPENSES_FETCHED_SUCCESSFULLY = 'EXPENSES_FETCHED_SUCCESSFULLY';
export const FETCHING_EXPENSES_FAILED = 'FETCHING_EXPENSES_FAILED';